print("Fearadust's Sensitivity Converter")
currentdpi = input("Enter your current DPI ")
currentsens = input("Enter your current sensitivity ")
newdpi = input("Enter your new DPI ")
currentdpi = float(currentdpi)
currentsens = float(currentsens)
newdpi = float(newdpi)
print("Your new sensitivity is " + str(currentdpi*currentsens/newdpi))
input("Enter any key to exit")